
OBJ	=	ogrgeomediadriver.obj ogrgeomediadatasource.obj ogrgeomedialayer.obj \
		ogrgeomediatablelayer.obj  ogrgeomediaselectlayer.obj

GDAL_ROOT	=	..\..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

EXTRAFLAGS = -DNOMINMAX -I.. -I..\.. -I..\pgeo

default:	$(OBJ)

clean:
	-del *.obj *.pdb
